AllCops:
  Include:
  - "**/*.rb"
  - "**/*.rake"
  - "**/Gemfile"
  - "**/Rakefile"
  Exclude:
  - "vendor/**/*"
  - "db/**/*"
  - "spec/rails_helper.rb"
  - "spec/spec_helper.rb"
  DisplayCopNames: false
  StyleGuideCopsOnly: false
Rails:
  Enabled: true

Rails/Delegate:
  Enabled: false
Rails/SkipsModelValidations:
  Exclude:
    - "lib/tasks/migrate.rake" # migrates usually updates without validation

Layout/AlignHash:
  EnforcedHashRocketStyle: table
  EnforcedColonStyle: table
Layout/AlignParameters:
  EnforcedStyle: with_fixed_indentation
Layout/IndentArray:
  EnforcedStyle: consistent
Layout/IndentHash:
  EnforcedStyle: consistent
Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented
Layout/SpaceBeforeBlockBraces:
  Enabled: false

Lint/ParenthesesAsGroupedExpression:
  Exclude:
    - "spec/**/*"

Naming/PredicateName:
  Exclude:
    - "spec/support/**/*"
  NamePrefixBlacklist:
    - 'is_'
Naming/AccessorMethodName:
  Exclude:
    - "app/controllers/**/*" # controllers may have methods with `set_` prefix
Naming/VariableNumber:
  Enabled: false
Naming/UncommunicativeMethodParamName:
  AllowedNames:
    - io
    - id
    - to
    - by
    - on
    - in
    - at
    - ex

Style/BracesAroundHashParameters:
  Enabled: false
Style/ClassAndModuleChildren:
  Enabled: false
Style/DoubleNegation:
  Enabled: false
Style/EmptyMethod:
  Exclude:
    - "app/controllers/**/*_controller.rb"
Style/FormatString:
  Enabled: false
Style/RaiseArgs:
  Enabled: false # looks like it works wrong
Style/RedundantReturn:
  Enabled: false
Style/TrailingCommaInArguments:
  Enabled: false
Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: consistent_comma
Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: consistent_comma

Performance/FixedSize:
  Exclude:
    - "spec/features/**/*"

Metrics/AbcSize:
  Enabled: false
Metrics/BlockLength:
  Exclude:
    - "config/routes.rb"
    - "spec/**/*"
Metrics/ClassLength:
  Max: 300
Metrics/LineLength:
  Enabled: false
Metrics/MethodLength:
  Max: 50

Documentation:
  Enabled: false
